apiVersion: apps/v1
kind: Deployment

metadata:
  name: olivetti-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: olivetti-app

  template:
    metadata:
      labels:
        app: olivetti-app

    spec:
      containers:
      - name: olivetti-app

        image: phanipervela/olivetti-face-app:v1

        ports:
        - containerPort: 5000
